//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExportExcel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WORK_HOURS_REPORT
    {
        public int PROJECT_ID { get; set; }
        public string EMPLOYEE_NAME { get; set; }
        public System.DateTime WORK_DATE { get; set; }
        public string CLIENT_NAME { get; set; }
        public string WORK_DESCRIPTION { get; set; }
        public Nullable<decimal> WORK_HOURS { get; set; }
        public Nullable<decimal> HOUR_COST { get; set; }
    }
}
